In [2]:
import numpy as np

# Numpy (2)
## 기타 주요 함수들

In [14]:
#array 정렬하기
a1 = np.array([[5, 9, 10, 3, 1], [8, 3, 4, 2, 5]])
print('before: \n',a1)
a1.sort(axis=0)
print('\nafter: \n',a1)

before: 
 [[ 5  9 10  3  1]
 [ 8  3  4  2  5]]

after: 
 [[ 5  3  4  2  1]
 [ 8  9 10  3  5]]


In [51]:
#중복된 요소 제거하기
a2 = np.array([1, 1, 2, 3, 3, 3, 1])
print(np.unique(array))

[1 2 3]


## 행렬 인덱싱 2
`np.where` 문을 활용한 인덱싱

In [62]:
#np.where
a3=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

np.where(a3>4)
#리턴값은 각각 조건을 만족하는 요소의 행 배열, 열 배열임

np.where((a3%2==0) & (a3>4)) #조건식은 꼭 괄호로 묶어 주기. and=&, or=|

(array([0, 1, 1, 1, 2, 2, 2]), array([1, 0, 1, 2, 0, 1, 2]))

In [65]:
#응용: 조건을 만족하는 요소만 출력하기
np.where(a3<6, np.nan, a3)

array([[nan, nan, nan],
       [nan, nan,  6.],
       [ 7.,  8.,  9.]])

In [10]:
#삼각함수 계산
np.sin(np.pi)
# np.cos(np.pi)
# np.tan(np.pi)

-1.2246467991473532e-16

## 다항식 연산
다항식을 만들 때는 `np.poly1d`를 사용합니다.

첫 번째 인자로 인수들의 배열을, 두 번째 인자로 근/계수 여부, 세 번째 인자로 변수명을 지정합니다.

- True 지정 시 각 인자들은 (다항식)=0을 충족하는 방정식의 근이 됩니다.
- False 지정 시 각 인자들은 다항식의 계수가 됩니다. 기본값은 False입니다.

In [70]:
np.poly1d([1,2], True, variable='x') #(x-1)(x-2)=0 OR x^2-3x+2=0
#variable은 지정하지 않으면 x가 기본

poly1d([ 1., -3.,  2.])

In [93]:
np.poly1d([1,2], False, variable='x') #x+2=0

poly1d([1, 2])

In [73]:
#2x^3-x+1=0을 구현해보자
np.poly1d()

poly1d([ 2,  0, -1,  1])

In [92]:
#해 계산: r 또는 np.roots
eq1=np.poly1d([2,1,-3], True) #(x-2)(x-1)(x+3)
print(eq1.r)
print(np.roots(eq1))

[-3.  2.  1.]
[-3.  2.  1.]


In [90]:
#polyval: 값을 넣어서 연산
np.polyval(eq1, 2)

0.0

In [96]:
#값 대신 식을 집어넣을 수도 있다
np.polyval(eq1,np.poly1d([1,2])) #((x+2)-2)((x+2)-1)((x+2)+3) = 0 즉 x(x+1)(x+5)=0

poly1d([1., 6., 5., 0.])

## 다항식의 연산, 미분과 적분

In [6]:
#다항식의 사칙연산
eq2=np.poly1d([1,2,3]) # x^2+2x+3
eq3=np.poly1d([2,7]) # 2x+7

print(np.polyadd(eq2, eq3),'\n')
print(np.polysub(eq2, eq3),'\n')
print(np.polymul(eq2, eq3),'\n')
print(np.polydiv(eq2, eq3),'\n') #몫-나머지 형태로 결과 반환

   2
1 x + 4 x + 10 

   2
1 x - 4 

   3      2
2 x + 11 x + 20 x + 21 

(poly1d([ 0.5 , -0.75]), poly1d([8.25])) 



In [108]:
#polyder: 미분
eq4=np.poly1d([2,1,-3])
print('미분 전:\n', eq4)


미분 전:
    2
2 x + 1 x - 3


In [117]:
eq4d=np.polyder(eq4, m=1)
print('\n1차 미분 후:', eq4d)


1차 미분 후:  
4 x + 1


In [112]:
#polyint: 적분
eq4=np.poly1d([2,1,-3])
print('적분 전:\n', eq4)

적분 전:
    2
2 x + 1 x - 3


In [115]:
eq4i=np.polyint(eq4, m=1, k=7)
print('1차 적분 후:\n', eq4i)

1차 적분 후:
         3       2
0.6667 x + 0.5 x - 3 x + 7
